---

# @todo
# - Create ~/Applications
# - Install keepassxc (Flatpak)
# - Install ONLYOFFICE (Flatpak)
# - Install VPNs
# - Install Spotify (Flatpak)
# - Install PDFArranger (Flatpak)
# - Install Firefox (if not already there)
# - Install apt-transport-https
# - Install flatpak

