---

- name: Setup Base system
  hosts: all
  tasks:
    - name: Create needed directories in ~
      ansible.builtin.file:
        name: "~/{{ item }}"
        state: directory
      loop:
        - Applications

    - name: Update apt and all packages
      block:
        - block:
          - name: Update cache
            become: true
            ansible.builtin.apt:
              update_cache: true
          - name: Upgrade packages
            become: true
            ansible.builtin.apt:
              upgrade: full
          when: ansible_pkg_mgr == 'apt'

        - block:
          - name: Upgrade packages
            become: true
            ansible.builtin.dnf:
              name: "*"
              state: latest
          when: ansible_pkg_mgr == 'dnf'

    - name: Install needed packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - apt-transport-https
        - flatpak
        - firefox
      when: ansible_distribution == 'Debian'

    - name: Install needed packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - flatpak
        - firefox
      when: ansible_distribution == 'Fedora'

    - name: Enable default flatpak repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    # @todo We can probably just add a variable somewhere and replace the hard-coded loop here.
    - name: Install flatpak software
      community.general.flatpak:
        method: user
        name: "{{ item }}"
      loop:
        - org.onlyoffice.desktopeditors
        - org.keepassxc.KeePassXC
        - com.spotify.Client
        - com.github.jeromerobert.pdfarranger
        - org.gnome.World.PikaBackup

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    # @see https://www.sublimetext.com/docs/linux_repositories.html
    - name: Install Sublime Text
      block:
        - block:
            - name: add gpg repo key
              become: true
              ansible.builtin.get_url:
                url: https://download.sublimetext.com/sublimehq-pub.gpg
                dest: /etc/apt/keyrings/sublime-text.asc
                mode: '0644'

            - name: add apt repo
              become: true
              ansible.builtin.apt_repository:
                repo: deb [signed-by=/etc/apt/keyrings/sublime-text.asc] https://download.sublimetext.com/ apt/stable/
                filename: sublime-text
          when: ansible_distribution == 'Debian'

        - block:
            - name: add gpg repo key
              become: true
              ansible.builtin.rpm_key:
                key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

            - name: add yum repo
              become: true
              ansible.builtin.yum_repository:
                baseurl: https://download.sublimetext.com/rpm/stable/x86_64
                name: sublime-text
                description: Sublime Text - x86_64 - Stable
                enabled: true
                gpgcheck: true
                gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
          when: ansible_distribution == 'Fedora'

        - name: Installing required packages
          become: true
          ansible.builtin.package:
            name: sublime-text

    - name: Utility Gnome settings
      ansible.builtin.command:
        cmd: "gsettings set {{ item.key }} {{ item.value }}"
      loop:
        - key: org.gnome.desktop.calendar show-weekdate
          value: 'true'
