---

- name: Setup Base system
  hosts: all
  tasks:
    - name: Create needed directories in ~
      ansible.builtin.file:
        name: "~/{{ item }}"
        state: directory
      loop:
        - Applications

    - name: Update apt and all packages
      block:
        - name: Update cache
          become: true
          ansible.builtin.apt:
            update_cache: true
        - name: Upgrade packages
          become: true
          ansible.builtin.apt:
            upgrade: full
      when: ansible_pkg_mgr == 'apt'

    - name: Install needed packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - apt-transport-https
        - flatpak
        - firefox

    - name: Enable default flatpak repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    # @todo We can probably just add a variable somewhere and replace the hard-coded loop here.
    - name: Install flatpak software
      community.general.flatpak:
        method: user
        name: "{{ item }}"
      loop:
        - org.onlyoffice.desktopeditors
        - org.keepassxc.KeePassXC
        - com.spotify.Client
        - com.github.jeromerobert.pdfarranger

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install Sublime Text
      block:
        - name: add gpg repo key
          become: true
          ansible.builtin.get_url:
            url: https://download.sublimetext.com/sublimehq-pub.gpg
            dest: /etc/apt/keyrings/sublime-text.asc
            mode: '0644'

        - name: add apt repo
          become: true
          ansible.builtin.apt_repository:
            repo: deb [signed-by=/etc/apt/keyrings/sublime-text.asc] https://download.sublimetext.com/ apt/stable/
            filename: sublime-text

        - name: Installing required packages
          become: true
          ansible.builtin.package:
            name: sublime-text
