---

- name: Setup Common system
  hosts: all

  tasks:
    - name: Create needed directories in ~
      ansible.builtin.file:
        name: "~/{{ item }}"
        state: directory
      loop:
        - Applications

    - name: Utility Gnome settings
      ansible.builtin.command:
        cmd: "gsettings set {{ item.key }} {{ item.value }}"
      loop:
        - key: org.gnome.desktop.calendar show-weekdate
          value: 'true'
        - key: org.gnome.desktop.privacy old-files-age
          value: '"uint32 30"'
        - key: org.gnome.desktop.privacy recent-files-max-age
          value: 30
        - key: org.gnome.desktop.peripherals.mouse accel-profile
          value: flat
        - key: org.gnome.desktop.peripherals.touchpad natural-scroll
          value: 'false'

    - name: Install gnome extensions
      ansible.builtin.debug:
        var: item
      loop:
        - https://extensions.gnome.org/extension/615/appindicator-support/
        - https://extensions.gnome.org/extension/2236/night-theme-switcher/

    - name: Remove libreoffice
      block:
        - name: Remove libreoffice
          become: true
          ansible.builtin.apt:
            name: libreoffice*
            state: absent
            autoremove: true
            purge: true
          when: ansible_pkg_mgr == 'apt'

        - name: Remove libreoffice
          become: true
          ansible.builtin.dnf:
            name: libreoffice*
            state: absent
            autoremove: true
            allowerasing: true
          when: ansible_pkg_mgr == 'dnf'

        - name: Remove libreoffice
          become: true
          ansible.builtin.dnf5:
            name: libreoffice*
            state: absent
            autoremove: true
            allowerasing: true
          when: ansible_pkg_mgr == 'dnf5'

  roles:
    - common