---

- name: Setup Common system
  hosts: all

  tasks:
    - name: Create needed directories in ~
      ansible.builtin.file:
        name: "~/{{ item }}"
        state: directory
      loop:
        - Applications

  roles:
    - common