---

- name: Setup Development systems
  hosts: all
  tasks:
    - name: Update apt and all packages
      become: true
      block:
        - name: Update cache
          ansible.builtin.apt:
            update_cache: true
        - name: Upgrade packages
          ansible.builtin.apt:
            upgrade: full
      when: ansible_pkg_mgr == 'apt'

    - name: Install and configure git
      block:
        # @todo Creation and copying of those files is not optimal. We can not account for changes
        # in the .gitconfig here. It would be better to either run `git config` OR have a custom `.gitconfig.custom`
        # and a file line check for .gitconfig.
        - name: Place config files in home directory
          ansible.builtin.copy:
            src: files/home/.gitconfig
            dest: ~/.gitconfig
            force: false # This file is very likely changed by the package installation

        - name: Place config files in home directory
          ansible.builtin.copy:
            src: "files/home/{{ item }}"
            dest: "~/{{ item }}"
          loop:
            - .gitconfig.github
            - .gitignore

        - name: Install git
          become: true
          ansible.builtin.package:
            name: git

    - name: Create needed directories in ~
      ansible.builtin.file:
        name: "~/{{ item }}"
        state: directory
      loop:
        - Applications
        - bin
        - Projects
        - Projects/work

    - name: Install nerdfonts
      block:
        - name: Make .fonts directory
          ansible.builtin.file:
            dest: ~/.local/share/fonts/NerdFonts
            state: directory

        - name: Download nerdfont
          ansible.builtin.unarchive:
            remote_src: true
            src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraMono.zip
            include:
              - FiraMonoNerdFontMono-Bold.otf
              - FiraMonoNerdFontMono-Medium.otf
              - FiraMonoNerdFontMono-Regular.otf
            dest: ~/.local/share/fonts/NerdFonts

    - name: Install starship
      block:
        - name: Check for Starship command
          ansible.builtin.command:
            cmd: which starship
          register: starship_installed
          ignore_errors: yes

        - name: Temporary location for installer file
          ansible.builtin.tempfile:
            suffix: starship_installer
          register: starship_temp_installer
          when: starship_installed.rc != 0

        - name: Download installer
          ansible.builtin.get_url:
            url: https://starship.rs/install.sh
            dest: "{{ starship_temp_installer.path }}"
            force: true # Because we have already created the temp file before
          when: starship_temp_installer.changed

        - name: Run installer
          ansible.builtin.script:
            cmd: "{{ starship_temp_installer.path }} --yes --bin-dir ~/bin"
            executable: /usr/bin/sh
            creates: ~/bin/starship
          when: starship_temp_installer.changed

        - name: Delete installer
          ansible.builtin.file:
            path: "{{ starship_temp_installer.path }}"
            state: absent
          when: starship_temp_installer.changed

    - name: Install IntelliJ IDEA Ultimate IDE
      ansible.builtin.debug:
        msg: This would install 'IntelliJ IDEA Ultimate IDE'
        # Possible collection: https://galaxy.ansible.com/ui/repo/published/diademiemi/jetbrains/
        # Place .desktop (~/.local/share/applications)

    # todo Maybe this is a base system thing?
    - name: Install Sublime Text
      become: true
      block:
        - name: add gpg repo key
          ansible.builtin.get_url:
            url: https://download.sublimetext.com/sublimehq-pub.gpg
            dest: /etc/apt/keyrings/sublime-text.asc
            mode: '0644'
            force: true

        - name: add apt repo
          ansible.builtin.apt_repository:
            repo: deb [signed-by=/etc/apt/keyrings/sublime-text.asc] https://download.sublimetext.com/ apt/stable/
            filename: sublime-text

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Installing required packages
          ansible.builtin.package:
            name: sublime-text

    - name: Configure terminal
      block:
        - name: Find default profiles name
          ansible.builtin.command:
            cmd: gsettings get org.gnome.Terminal.ProfilesList default
          register: gnome_terminal_default_profile

        - name: Configure terminal's default profile
          block:
            # Maybe add a loop here with a check, so we do not run this every time.
            - name: Set nerdfont
              ansible.builtin.command:
                cmd: "gsettings set {{gnome_terminal_default_profile_gsettings_path}}/ font 'FiraMono Nerd Font Mono 12'"

            - name: Set shell to be login shell
              ansible.builtin.command:
                cmd: "gsettings set {{gnome_terminal_default_profile_gsettings_path}}/ login-shell true"
          vars:
            gnome_terminal_default_profile_gsettings_path: "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gnome_terminal_default_profile.stdout }}"

    - name: Configure shell
      block:
        - name: Place bash config files
          ansible.builtin.copy:
            src: "files/home/{{ item }}"
            dest: "~/{{ item }}"
          loop:
            - .bash_paths
            - .bash_profile

        - ansible.builtin.debug:
            msg: This would configure the shell
            # - Install neofetch

    - name: Install virtualbox
      ansible.builtin.debug:
        msg: This would install virtualbox

    - name: Install vagrant
      ansible.builtin.debug:
        msg: This would install vagrant

    - name: Install docker
      ansible.builtin.debug:
        msg: This would install docker

    - name: Install Insomnia (Flatpak)
      ansible.builtin.debug:
        msg: This would install Insomnia (Flatpak)
